package fancybank.gui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author xiekangxian
 */
public class StockEditPage extends javax.swing.JFrame {

        /**
         * Creates new form StockEditPage
         */
        public StockEditPage() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                javax.swing.JScrollPane list = new javax.swing.JScrollPane();
                stock_table = new javax.swing.JTable();
                jPanel1 = new javax.swing.JPanel();
                javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
                javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
                add_stock_name_text = new javax.swing.JTextField();
                javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
                add_stock_num_text = new javax.swing.JTextField();
                javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
                add_stock_price_text = new javax.swing.JTextField();
                add_button = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
                delete_button = new javax.swing.JButton();
                javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
                javax.swing.JLabel nothing = new javax.swing.JLabel();
                javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
                edit_price_text = new javax.swing.JTextField();
                edit_button = new javax.swing.JButton();
                back_button = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Edit Stock");

                stock_table.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Stock Name", "Stock Number", "Current Price"
                                }));
                list.setViewportView(stock_table);

                jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Add Stock");

                jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("Stock Name :");

                add_stock_name_text.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                add_stock_name_textActionPerformed(evt);
                        }
                });

                jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText("Stock Number :");

                add_stock_num_text.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                add_stock_num_textKeyTyped(evt);
                        }
                });

                jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
                jLabel4.setText("Stock Price :");

                add_stock_price_text.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                add_stock_price_textKeyTyped(evt);
                        }
                });

                add_button.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
                add_button.setText("Add");
                add_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                add_buttonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                101,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(36, 36, 36)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(6, 6, 6)
                                                                                                                                .addComponent(jLabel3,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                111,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(add_stock_num_text,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                153,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel2,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                111,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(add_stock_name_text)))))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(add_button,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                84,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(add_stock_price_text,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                151,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(97, 97, 97)));

                jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
                                new java.awt.Component[] { add_stock_name_text, add_stock_num_text,
                                                add_stock_price_text });

                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                23,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(add_stock_price_text,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(add_stock_name_text,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                23,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(add_stock_num_text,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(add_button))
                                                                .addGap(0, 11, Short.MAX_VALUE)));

                jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                jLabel5.setText("Delete Stock");

                delete_button.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
                delete_button.setText("Delete Selected Row");
                delete_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                delete_buttonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                107,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(604, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(delete_button,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                348,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(175, 175, 175)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(delete_button)
                                                                .addContainerGap(20, Short.MAX_VALUE)));

                jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                nothing.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
                nothing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                nothing.setText("Edit Price");

                jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
                jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel8.setText("New Price :");

                edit_button.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
                edit_button.setText("Edit Selected Stock Price");
                edit_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                edit_buttonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(9, 9, 9)
                                                                                                .addComponent(nothing,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                84,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(35, 35, 35)
                                                                                                .addComponent(jLabel8,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                102,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(edit_price_text,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                153,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(61, 61, 61)
                                                                                                .addComponent(edit_button,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                276,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(72, Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(nothing)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel8,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                23,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(edit_price_text,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(edit_button,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                32,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(24, Short.MAX_VALUE)));

                back_button.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
                back_button.setText("Back");
                back_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                back_buttonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(64, 64, 64)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                false)
                                                                                                                .addComponent(jPanel2,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jPanel1,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(list,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jPanel3,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(305, 305, 305)
                                                                                                .addComponent(back_button,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                228,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(65, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(40, 40, 40)
                                                                .addComponent(list,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                370,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(32, 32, 32)
                                                                .addComponent(back_button,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(32, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void add_stock_name_textActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_add_stock_name_textActionPerformed
                // TODO add your handling code here:

        }// GEN-LAST:event_add_stock_name_textActionPerformed

        private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_add_buttonActionPerformed
                // TODO add your handling code here:
                String stock_name = this.add_stock_name_text.getText();
                String stock_num = this.add_stock_num_text.getText();
                String stock_price = this.add_stock_price_text.getText();
                if (stock_name.isEmpty() || stock_num.isEmpty() || stock_price.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Please enter all fields.", "Empty Input Exist",
                                        JOptionPane.ERROR_MESSAGE);
                } else {
                        DefaultTableModel table = (DefaultTableModel) stock_table.getModel();
                        table.addRow(new Object[] { stock_name, stock_num, stock_price });
                }
                this.add_stock_name_text.setText("");
                this.add_stock_num_text.setText("");
                this.add_stock_price_text.setText("");
                // perform add
        }// GEN-LAST:event_add_buttonActionPerformed

        private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_delete_buttonActionPerformed
                // TODO add your handling code here:
                int row = stock_table.getSelectedRow();
                if (row < 0) {
                        JOptionPane.showMessageDialog(null, "No stock is selected.", "No selection",
                                        JOptionPane.ERROR_MESSAGE);
                } else {
                        DefaultTableModel table = (DefaultTableModel) stock_table.getModel();
                        table.removeRow(row);
                }
        }// GEN-LAST:event_delete_buttonActionPerformed

        private void add_stock_num_textKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_add_stock_num_textKeyTyped
                // TODO add your handling code here:
                char enter = evt.getKeyChar();
                if (!(Character.isDigit(enter))) {
                        evt.consume();
                }
        }// GEN-LAST:event_add_stock_num_textKeyTyped

        private void add_stock_price_textKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_add_stock_price_textKeyTyped

                char enter = evt.getKeyChar();
                if ((!(Character.isDigit(enter))) && enter != '.') {
                        evt.consume();
                }
        }// GEN-LAST:event_add_stock_price_textKeyTyped

        private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_back_buttonActionPerformed
                // TODO add your handling code here:
                setVisible(false);
                dispose();
        }// GEN-LAST:event_back_buttonActionPerformed

        private void edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_edit_buttonActionPerformed
                String stock_price = this.edit_price_text.getText();
                this.edit_price_text.setText("");
                int row = stock_table.getSelectedRow();
                if (row < 0) {
                        JOptionPane.showMessageDialog(null, "No stock is selected.", "No selection",
                                        JOptionPane.ERROR_MESSAGE);
                } else {
                        DefaultTableModel table = (DefaultTableModel) stock_table.getModel();
                        table.setValueAt(stock_price, row, 2);
                }
        }// GEN-LAST:event_edit_buttonActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(StockEditPage.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(StockEditPage.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(StockEditPage.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(StockEditPage.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new StockEditPage().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton add_button;
        private javax.swing.JTextField add_stock_name_text;
        private javax.swing.JTextField add_stock_num_text;
        private javax.swing.JTextField add_stock_price_text;
        private javax.swing.JButton back_button;
        private javax.swing.JButton delete_button;
        private javax.swing.JButton edit_button;
        private javax.swing.JTextField edit_price_text;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JTable stock_table;
        // End of variables declaration//GEN-END:variables
}
